config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  resources :tracks

  get '/recent' => "ajax#recent"
  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

  get 'search_artist' => 'ajax#search_by_artist'  , :as => :search_by_artist
  get 'add_song' => 'ajax#add_song'
  get 'add_song_to_track' => 'ajax#add_song_to_track'
  post 'update_profile' => 'users#update_profile'

end

app/models/track.rb
class Track < ActiveRecord::Base

  has_many :playlist_tracks
  has_many :playlists,:through => :playlist_tracks
  has_many :likes

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    unless params[:playlist_id].nil?
      @playlist = Playlist.find_by_id(params[:playlist_id])
      @tracks = @playlist.tracks
      @genres = Genre.all
    else
      @tracks = Track.all
      @genres = Genre.all
    end
  end

  def new
    @track = Track.new
    @genres = Genre.all
  end

  def create
    unless params[:playlist_id].nil?
      @play_list = Playlist.find_by_id(params[:playlist_id])
      @track = Track.create(track_params)
      @track.playlist_tracks.create(playlist: @play_list, user_id: current_user.id)
    else
      @track = Track.create(track_params)
    end
    respond_to do |format|
      if @track
        format.html { redirect_to params[:playlist_id].nil? ? tracks_path : playlist_tracks_path(params[:playlist_id]), alert: 'Track was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    Track.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to params.has_key?(:playlist_id) ? playlist_tracks_url(params[:playlist_id]): tracks_url, :alert => "Track Deleted Successfully." }
      format.json { head :no_content }
    end
  end

    private

    def track_params
      params.require(:track).permit(:title, :artist, :url, :image, :large_img, :small_img, :via, :via_url, :background, :combined_truncated)
    end
end

app/views/tracks/index.html.erb
<div class="container">
    <% unless params[:playlist_id].nil? %>
      <h1>Playlist <%= @playlist.name %> </h1>
    <% else %>
      <h1 style="float: left">Tracks </h1>
      <span style="width: 150px; padding: 6px; float: right; margin-right: -66px;">
        <button class="btn btn-primary" class="add_music" data-toggle="modal" data-target="#myModal">Add Music</button>
      </span>
      <%= form_tag(search_by_artist_path, :method => "get", class: "navbar-form", id: "search-form", style: "float:right") do %>
          <div class="input-append">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Artist Name" %>
            <button class="btn btn-primary" type="submit">Search </button>
          </div>
      <% end %>
    <% end %>
</div>

<div class="container">
    <table class="table table-striped table-bordered">
      <thead>
        <th><b>#</b></th>
        <th><b>Title</b></th>
        <th><b>Artist</b></th>
        <th><b>URL</b></th>
        <th><b>Image</b></th>
        <th><b>Large Image</b></th>
        <th><b>Small Image</b></th>
        <th><b>Via</b></th>
        <th><b>Via URL</b></th>
        <th><b>Background</b></th>
        <th><b>Combined Truncated</b></th>
      </thead>

      <%- unless @tracks.nil? %>
        <%- @tracks.each_with_index do |track,index| %>
         <tr>
           <td><%= index+1%>  </td>
           <td><%= track.title%>  </td>
           <td><%= track.artist%></td>
           <td><%= track.url%> </td>
           <td><%= image_tag(track.image, height: '40', width: '40') %></td>
           <td><%#= track.large_img %> </td>
           <td><%= track.small_img %></td>
           <td><%= track.via %> </td>
           <td><%= track.via_url %> </td>
           <td><%= track.background %>   </td>
           <td><%= track.combined_truncated %> </td>
           <td><%= link_to image_tag("/assets/delete.jpg", height: '20', width: '20'), params[:playlist_id].nil? ? track_path(track.id) : playlist_track_path(params[:playlist_id],track.id), :method => :delete, 'data-toggle' => "tooltip", :title => "Delete"   %></td>
         </tr>
        <%- end %>
      <%- end %>
    </table>
</div>

<%= link_to 'New Track', params[:playlist_id].nil? ? new_track_path : new_playlist_track_path(params[:playlist_id]), class: "btn btn-primary", :style => "margin-left:95px;margin-bottom:30px"   %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Add Music</h3>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control" id ="song" placeholder="Search for a song or provide link...">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="next_btn">Next</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Add Music</h3>
      </div>
      <div class="modal-body">
        <div class="well" style="width: 159px; padding: 10px; height: 165px;" id="song_image"> <image src='' height=144 width=137 /></div>
        <div class="form-group">
          <label class="sr-only">Artist</label>
          <input type="text" class="form-control" id="artist" placeholder="Artist">
        </div>
        <div class="form-group">
          <label class="sr-only">Song</label>
          <input type="text" class="form-control" id="song_name" placeholder="Song">
        </div>

        <div class="form-group">
          <div>
            <%= select_tag("genre", options_from_collection_for_select(@genres, "id", "name"),:class=>"form-control") %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit_btn">Submit</button>
      </div>
    </div>
  </div>
</div>
<div id="load-ajax"></div>
<div id="songs_list"></div>

<script type="text/javascript">
    $('#next_btn').click(function(){
        var url = $('#song').val()
        if(url == ""){
            alert('First Enter the URL')
        }else{
            var target = document.getElementById('load-ajax')
            var spinner = new Spinner().spin()
            target.appendChild(spinner.el)
            $('#myModal').data('bs.modal').isShown = false;
            $.ajax({
                type:'get',
                url: '/add_song',
                data: 'url='+url,
                success: function(response){
                    $('#artist').val(response.data['author_name'])
                    $('#song_name').val(response.data['title'])
                    $('#song_image img').attr('src',response.data['thumbnail_url'])
                    $('#myModal').data('bs.modal').isShown = true
                    target.removeChild(spinner.el);
                    $('#myModal').modal('hide');
                    $('#submitModal').modal('show');

                },
                error: function(){
                    $('#myModal').data('bs.modal').isShown = true
                    target.removeChild(spinner.el);
                    $('#myModal').modal('hide');
                    alert('Sorry, something has gone wrong with response. please try later')
                }
            })
        }
    })

   $('#submit_btn').click(function(){
       var url = $('#song').val()
       var target = document.getElementById('load-ajax')
       var spinner = new Spinner().spin()
       target.appendChild(spinner.el)
       $('#submitModal').data('bs.modal').isShown = false;

       $.ajax({
           type:'get',
           url: '/add_song',
           data: 'url='+url,
           success: function(response){
               $('#songs_list').append("<div class='item' style='width:200px;border:1px solid #808080; margin-bottom:10px;padding:10px'>"+response.data['html']+"</div>")
               var container = document.querySelector('#songs_list');
               var msnry = new Masonry( container, {
                   // options
                   itemSelector: '.item',
                   "gutter" : 10
               });
               $('#songs_list .item iframe').height(250)
               $('#submitModal').data('bs.modal').isShown = true
               target.removeChild(spinner.el);
               $('#submitModal').modal('hide');
               window.location.href = window.location.pathname+"#songs_list"
           },
           error: function(){
               $('#submitModal').data('bs.modal').isShown = true
               target.removeChild(spinner.el);
               $('#submitModal').modal('hide');
               alert('Sorry, something has gone wrong with response. please try later')
           }
       })
   })
</script>

app/views/tracks/new.html.erb
<div class="container">
  <h1> New Track</h1>
  <div class="form-group well">
    <%= form_for @track, url: {action: "create", controller: "tracks"}, :html => {:class => "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :title, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
        </div>
      </div>

        <div class="form-group">
          <%= f.label :artist, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :artist, class: "form-control", placeholder: "Artist" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :combined_truncated, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :combined_truncated, class: "form-control", placeholder: "Combined Truncated" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :large_img, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :large_img, class: "form-control", placeholder: "Large Image" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :medium_img, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :medium_img, class: "form-control", placeholder: "Medium Image" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :small_img, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :small_img, class: "form-control", placeholder: "Small Image" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :via, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :via, class: "form-control", placeholder: "Via" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :url, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :url, class: "form-control", placeholder: "Url" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :background, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :background, class: "form-control", placeholder: "Background" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :genre, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= select_tag("genre", options_from_collection_for_select(@genres, "id", "name")) %>
          </div>
        </div>

      <div class="actions"><%= f.submit 'Save', class: "btn btn-primary"  %></div>

    <%- end %>
</div>
</div>