config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  resources :tracks

  get '/recent' => "ajax#recent"
  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

  get 'search_artist' => 'ajax#search_by_artist'  , :as => :search_by_artist
  get 'add_song' => 'ajax#add_song'
  get 'add_song_to_track' => 'ajax#add_song_to_track'
  post 'update_profile' => 'users#update_profile'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def landing
    if user_signed_in?
      redirect_to "/users/edit"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/landing.html.erb
<%= render "layouts/header" %>
                    <div id="step1" class="headerin">
                    	<div align="center" style="height:450px;">
                        <p>We are a points-based music promotion and discovery collective where you can
 build credibility while promoting music you think deserves to be heard. </p>
     					<div class="btns">
                        	<a class="learn_more" href="#learnMore"><span>Learn More &nbsp;&nbsp;<i class="fa fa-caret-down"></i></span></a>
                            <a class="get_acc" id="registerBtn">Get Early Access</a>


                     	</div>
                     </div>
                    </div>
                    <div id="step2">

						<div align="center" style="height:450px;">
							<div class="content" id="earlyAccesText">
							<h1>Early Access Registration</h1><br>
							</div>
							<div class="content" id="registerForm">

								<h3 style="height:40px;">Choose one of the following for an invite</h3>
								<div id="connections">
									<%= render :partial => "devise/shared/connections" %>
								</div>
							</div>
						</div>
					</div>
					<div id="step3">
						<div align="center" style="height:450px;">
							<div>
						<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
						  <%= devise_error_messages! %>

						  <div><br />
						  <%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "inputBox" %></div><br>

						  <div>
						  <%= f.password_field :password, :placeholder => "Password", :class => "inputBox"  %></div><br>

						  <div>
						  <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "inputBox"  %></div>

						  <div class="btns" style="width:300px;"><br><%= f.submit "Sign Up", :class =>"learn_more", :style => "color: #FFF;font-size: 28px;font-family: 'Montserrat', sans-serif;font-weight: 400;background: url(../images/learn-more-bg.png) no-repeat 225px 14px; display: block; height:75px;" %></div>
						<% end %>
						<!--

						<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
						  <div><%= f.label :email %><br />
						  <%= f.email_field :email, :autofocus => true %></div>

						  <div><%= f.label :password %><br />
						  <%= f.password_field :password %></div>

						  <% if devise_mapping.rememberable? -%>
						    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
						  <% end -%>

						  <div><%= f.submit "Login" %></div>
						<% end %>
						-->
						</div>
					</div>
				</div>





                         
<%= render "layouts/footer" %>