config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  resources :tracks

  get '/recent' => "ajax#recent"
  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

  get 'search_artist' => 'ajax#search_by_artist'  , :as => :search_by_artist
  get 'add_song' => 'ajax#add_song'
  get 'add_song_to_track' => 'ajax#add_song_to_track'
  post 'update_profile' => 'users#update_profile'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  belongs_to :user
  has_many :followers
  has_many :playlist_tracks
  has_many :tracks, :through => :playlist_tracks

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
      @playlists = User.find(current_user.id).playlists
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = current_user.playlists.new(:name => params[:playlist][:name])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlists_path, alert: 'Playlist was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    Playlist.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to playlists_path, :alert => "Playlist Deleted Successfully." }
      format.json { head :no_content }
    end
  end
end

app/views/playlists/index.html.erb
<div class="container">
    <h1>Playlist</h1>
    <table class="table table-striped table-bordered">
      <thead>
        <th><b>#</b></th>
        <th><b>Playlist Name</b><th>
      </thead>

      <%- unless @playlists.nil? %>
          <%- @playlists.each_with_index do |obj,index| %>
           <tr>
              <td><%= index+1 %></td>
              <td><%= link_to obj.name, playlist_tracks_path(obj.id)%></td>
             <td><%= link_to image_tag("/assets/delete.jpg", height: '20', width: '20'), playlist_path(obj.id), :method => :delete, 'data-toggle' => "tooltip", :title => "Delete"  %></td>
           </tr>
          <%- end %>
      <%- end %>
    </table>
<%= link_to 'New Playlist', new_playlist_path(params[:id]), class: "btn btn-primary" %>
</div>

app/views/playlists/new.html.erb
<div class="container">
    <h1> New Playlist</h1>
    <div class="form-group well">
        <%= form_for @playlist, url: {action: "create", controller: "playlists"}, class: "form-horizontal", role: "form" do |f| %>
            <%= f.label :name, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :name, class: "form-control", placeholder: "Playlist Name" %>
            </div>
            <div class="actions"><%= f.submit 'Save', class: "btn btn-primary" %></div>
        <%- end %>
    </div>
</div>