config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  resources :tracks

  get '/recent' => "ajax#recent"
  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

  get 'search_artist' => 'ajax#search_by_artist'  , :as => :search_by_artist
  get 'add_song' => 'ajax#add_song'
  get 'add_song_to_track' => 'ajax#add_song_to_track'
  post 'update_profile' => 'users#update_profile'

end

app/models/follower.rb
class Follower < ActiveRecord::Base

  belongs_to :user
  belongs_to :playlist

end

app/models/genre.rb
class Genre < ActiveRecord::Base

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    identity = find_by(provider: auth.provider, uid: auth.uid)
    if identity.nil?
      identity = create(uid: auth.uid, provider: auth.provider)
    end
    identity
    end
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :user
  belongs_to :track

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  belongs_to :user
  has_many :followers
  has_many :playlist_tracks
  has_many :tracks, :through => :playlist_tracks

end

app/models/playlist_track.rb
class PlaylistTrack < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base

  has_many :playlist_tracks
  has_many :playlists,:through => :playlist_tracks
  has_many :likes

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :followers
  has_many :playlists
  has_many :likes
  has_many :tracks, :through => :likes

TEMP_EMAIL = 'change@me.com'
TEMP_EMAIL_REGEX = /change@me.com/

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  mount_uploader :profile_pic, ProfilePicUploader
  mount_uploader :cover_pic, CoverPicUploader

def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)
    user = identity.user
    if user.nil?

      # Get the existing user from email if the OAuth provider gives us an email
      user = User.where(:email => auth.info.email).first if auth.info.email

      # Create the user if it is a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: auth.info.email.blank? ? TEMP_EMAIL : auth.info.email,
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end

      # Associate the identity with the user if not already
      if identity.user != user
        identity.user = user
        identity.save!
      end
    end
    user
  end

end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
  include HTTParty
  base_uri 'http://api.thisismyjam.com'

  def search_by_artist
    @qry_parameter =   params[:search]  if   params[:search]
    @tracks_data  =   tracks(@qry_parameter)
    @results = @tracks_data.parsed_response
  end

  def tracks(query)
    options =  { query: {by: 'artist', q: query} }
    self.class.get("/1/search/jam.json", options)
  end

  def add_song
    client = Soundcloud.new(:client_id => '2e16946fdb254e50750412d3d7c34b57')

    track_url = params[:url]
    embed_info = client.get('/oembed', :url => track_url)

    @data = embed_info
    session[:html] = @data['html']
    render :json => {:data => @data}.to_json
  end

  def add_song_to_track

    @track = Track.create(
        :title => params[:title],
        :artist => params[:artist],
        :url => params[:author_url],
        :image => params[:image],
        :large_img => session[:html],
        :via => params[:provider_name],
        :via_url => params[:provider_url],
    )
    render :json => {:status => "ok"}.to_json
  end

  def recent
    @tracks = Track.all
    render :layout => false
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

end

app/controllers/likes.rb
class LikesController < ApplicationController

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user  = current_user unless current_user.nil?
    @genres = Genre.all
    redirect_to root_url, :flash => { :alert => "You are not Invited User" } if current_user.invite_user == false
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    unless params[:playlist_id].nil?
      @playlist = Playlist.find_by_id(params[:playlist_id])
      @tracks = @playlist.tracks
      @genres = Genre.all
    else
      @tracks = Track.all
      @genres = Genre.all
    end
  end

  def new
    @track = Track.new
    @genres = Genre.all
  end

  def create
    unless params[:playlist_id].nil?
      @play_list = Playlist.find_by_id(params[:playlist_id])
      @track = Track.create(track_params)
      @track.playlist_tracks.create(playlist: @play_list, user_id: current_user.id)
    else
      @track = Track.create(track_params)
    end
    respond_to do |format|
      if @track
        format.html { redirect_to params[:playlist_id].nil? ? tracks_path : playlist_tracks_path(params[:playlist_id]), alert: 'Track was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    Track.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to params.has_key?(:playlist_id) ? playlist_tracks_url(params[:playlist_id]): tracks_url, :alert => "Track Deleted Successfully." }
      format.json { head :no_content }
    end
  end

    private

    def track_params
      params.require(:track).permit(:title, :artist, :url, :image, :large_img, :small_img, :via, :via_url, :background, :combined_truncated)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :add_email, :except => [:update_invite_user_status, :update_profile]

  def update_invite_user_status
    @user = User.find(params[:user_id])
    @user.update_attribute('invite_user',params[:status])
    UserMailer.invite_user(@user).deliver if @user.invite_user == true
    render :json => {:status => "ok"}.to_json
  end

  def add_email
    if params[:user] && params[:user][:email]
      current_user.email = params[:user][:email]
      current_user.skip_reconfirmation! # don't forget this if using Devise confirmable
      respond_to do |format|
        if current_user.save
          format.html { redirect_to current_user, notice: 'Your email address was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { @show_errors = true }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update_profile
    @user = current_user
    @user.update_attributes(:profile_pic => params[:user][:profile_image],:cover_pic => params[:user][:cover_image],:profile_name => params[:user][:profile_name],:facebook_link => params[:user][:facebook_link], :twitter_link => params[:user][:twitter_link],:website_link=>params[:user][:website_link],:location =>params[:user][:location])
    redirect_to :back
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def landing
    if user_signed_in?
      redirect_to "/users/edit"
    end
  end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def devise_mapping
	  Devise.mappings[:user]
	end

	def resource_name
	  devise_mapping.name
	end

	def resource_class
	  devise_mapping.to
	end
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_add_music.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Add Music</h3>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control" id ="song" placeholder="Search for a song or provide link...">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="next_btn">Next</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Add Music</h3>
      </div>
      <div class="modal-body">
        <div class="well" style="width: 159px; padding: 10px; height: 165px;" id="song_image"> <image src='' height=144 width=137 /></div>
        <div class="form-group">
          <label class="sr-only">Artist</label>
          <input type="text" class="form-control" id="artist" placeholder="Artist">
        </div>
        <div class="form-group">
          <label class="sr-only">Song</label>
          <input type="text" class="form-control" id="song_name" placeholder="Song">
        </div>

        <input type="hidden" id="provider_name" value=""/>
        <input type="hidden" id="provider_url" value=""/>
        <input type="hidden" id="html" value=""/>
        <input type="hidden" id="author_name" value=""/>
        <input type="hidden" id="author_url" value=""/>
        <div class="form-group">
          <div>
            <%= select_tag("genre", options_from_collection_for_select(@genres, "id", "name"),:class=>"form-control") %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit_btn">Submit</button>
      </div>
    </div>
  </div>
</div>

<div id="songs_list"></div>

<script type="text/javascript">
    $('document').ready(function(){
        $('#recent_songs').click(function(){
            var src = $(this)
            if(src.hasClass('active') == false){
                var target = document.getElementById('load-ajax')
                var spinner = new Spinner().spin()
                target.appendChild(spinner.el)
                $.ajax({
                    type: 'get',
                    url: '/recent',
                    success: function(response){
                        $('nav button.active').removeClass('active')
                        src.addClass('active')
                        $('#main').html(response)
                        var container = document.querySelector('.recent_tracks');
                        var msnry = new Masonry( container, {
                            itemSelector: '.box',
                            "gutter" : 10
                        });
                        target.removeChild(spinner.el);
                    }
                })
            }
        })
    })
    $('#next_btn').click(function(){
        var url = $('#song').val()
        if(url == ""){
            alert('First Enter the URL')
        }else{
            var target = document.getElementById('load-ajax')
            var spinner = new Spinner().spin()
            target.appendChild(spinner.el)
            $('#myModal').data('bs.modal').isShown = false;
            $.ajax({
                type:'get',
                url: '/add_song',
                data: 'url='+url,
                success: function(response){
                    $('#artist').val(response.data['author_name'])
                    $('#song_name').val(response.data['title'])
                    $('#song_image img').attr('src',response.data['thumbnail_url'])
                    $('#provider_name').val(response.data['provider_name']);
                    $('#provider_url').val(response.data['provider_url']);
                    $('#html').val(response.data['html'])
                    $('#author_name').val(response.data['author_name'])
                    $('#author_url').val(response.data['author_url'])
                    $('#myModal').data('bs.modal').isShown = true
                    target.removeChild(spinner.el);
                    $('#myModal').modal('hide');
                    $('#submitModal').modal('show');

                },
                error: function(){
                    $('#myModal').data('bs.modal').isShown = true
                    target.removeChild(spinner.el);
                    $('#myModal').modal('hide');
                    alert('Sorry, something has gone wrong with response. please try later')
                }
            })
        }
    })

    $('#submit_btn').click(function(){
        var url = $('#song').val()
        var target = document.getElementById('load-ajax')
        var spinner = new Spinner().spin()
        target.appendChild(spinner.el)
        $('#submitModal').data('bs.modal').isShown = false;
        var artist = $('#artist').val()
        var title = $('#song_name').val()
        var image = $('#song_image img').attr('src')
        var provider_name = $('#provider_name').val();
        var provider_url = $('#provider_url').val();
        var html = $('#html').val()
        var author_name = $('#author_name').val()
        var author_url = $('#author_url').val()
        $.ajax({
            type:'get',
            url: '/add_song_to_track',
            data: 'title='+title+'&image='+image+'&provider_name='+provider_name+'&provider_url='+provider_url+'&author_name='+author_name+'&artist='+artist+'&author_url='+author_url,
            success: function(response){
                $('.recent_tracks').append("<div class='box' style='border:1px solid #808080; margin-bottom:10px;padding:10px'><div class='cover'><img height='110' width='100' src=' "+image+" '/></div><div class='song-info'><span class='the-artist' style='font-size:10'>"+artist+"</span></div>")
                var container = document.querySelector('.recent_tracks');
                var msnry = new Masonry( container, {
                    // options
                    itemSelector: '.box',
                    "gutter" : 10
                });
                $('.menu-item-thumb-con iframe').last().height(166)
                $('#submitModal').data('bs.modal').isShown = true
                target.removeChild(spinner.el);
                $('#submitModal').modal('hide');
                $('.modal-backdrop').remove()
//                window.location.href = window.location.pathname+"#songs_list"
            },
            error: function(){
                $('#submitModal').data('bs.modal').isShown = true
                target.removeChild(spinner.el);
                $('#submitModal').modal('hide');
                $('.modal-backdrop').remove()
                alert('Sorry, something has gone wrong with response. please try later')
            }
        })
    })
</script>

app/views/layouts/_appFooter.html.erb
<div class="right" align="right">
    <button id="random"><i class="fa fa-random"></i></button>
    <button id="repeat"><i class="fa fa-repeat"></i></button>
    <button id="favorite"><i class="fa fa-heart"></i></button>
    <button id="add"><i class="fa fa-plus"></i></button>
    <button id="share"></button>
   <!-- <button id="options" class="btn-menu-state"><i class="fa fa-ellipsis-v"></i></button>-->
    <button id="options" class="btn-menu-state"><i class="fa fa-ellipsis-v"></i></button></div>


<script>
/*jQuery(document).ready(function ($) {
var settings_ap = {
disable_volume: 'off'
,disable_scrub: 'default'
,design_skin: 'skin-wave'
,skinwave_dynamicwaves:'on'
};
dzsag_init('#ag1',{
'transition':'fade'
,'autoplay' : 'on'
 ,design_menu_position:'bottom'
,'settings_ap':settings_ap
,design_menu_state:'on'
,design_menu_show_player_state_button: 'off'
 ,soundcloud_apikey:"8efdf99c13bf826f158503c1ebb9154c"
  ,php_retriever:"soundcloudretriever.php"
 });
alert(arr_menuitems);
});*/

</script>

<script>jQuery(document).ready(function ($) {
                        var settings_ap = {
                            design_skin: "skin-wave"
                            ,skinwave_dynamicwaves:"off"
                            ,skinwave_enableSpectrum:"off"
                            ,settings_backup_type:"full"
                            ,skinwave_enableReflect:"off"
                            ,skinwave_comments_enable:"off"
                            ,soundcloud_apikey:"8efdf99c13bf826f158503c1ebb9154c"
                            ,php_retriever:"soundcloudretriever.php"
                          };
                        dzsag_init("#ag1",{
                            "transition":"fade"
                            ,"autoplay" : "on"
                            ,"autoplayNext" : "on"
                            ,design_menu_position :"bottom"
                            ,disable_player_navigation:"off"
                            ,"settings_ap":settings_ap,
              cueFirstMedia:"on",
              design_menu_state:"open",
              design_menu_show_player_state_button:"off"});});</script>
</body>
</html>

app/views/layouts/_footer.html.erb
 <div class="clear"></div>
                    </div>
        		</div>
             </div>

            <!-- Header ends -->

            <!-- maincontent Starts -->
           	<div class="main_cont">
                	<div class="main_cont_in">
                    	<div class="column_blocks">
                        	<ul>
                            	<li>
                                	<a name="learnMore"><%= image_tag "icon1.png", alt: "Discover" %>
                                    <span>Discover</span>
                                    <p> You get a chance to
promote music  you think
deserves to be heard.</p>
                                </li>
                                <li class="colla">
                                	<%= image_tag "icon2.png", alt: "Collaborate" %>
                                    <span>Collaborate</span>
                                    <p>Interact in a fun,
collaborative manner with
other users and artists.</p>
                                </li>
                                <li class="last">
                                	<%= image_tag "icon3.png", alt: "Promote" %>
                                    <span>Promote</span>
                                    <p>Share music that is
essential to you and
deserves attention.</p>
                                </li>
                            </ul><div class="clear"></div>
                        </div>

                        <div class="mac"><a href="#"><%= image_tag "mac-img.png", alt: "mac" %></a></div>
                    </div>
                </div>
            <!-- maincontent ends -->

            <!-- footer starts -->
            <div class="footer">
            </div>
            <!-- footer ends -->



</div>
<!-- wrapper ends -->

</body>
</html>

app/views/layouts/_header.html.erb
<%= csrf_meta_tag %>
<!-- SET: FAVICON -->
<%= favicon_link_tag 'favicon.ico' %>
<!-- END: FAVICON -->
<!-- SET: STYLESHEET -->
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'header', media: 'all' %>
<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Montserrat:400,700" %>
<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" %>
<%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" %>
<!-- END: STYLESHEET -->

<!-- SET: SCRIPTS -->
<%= javascript_include_tag 'application' %>
<%= yield :javascript_includes %>
	<script type="text/javascript">

		$(document).ready(function(){
		 $(".angle_list a").click(function(){

		$(".angle_hover").slideToggle();
				});

		});

    </script>
<!-- END: SCRIPTS -->

<!--[if lt IE 9]>
 <style>
.header		 			{filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='images/laptop-bg.png',sizingMethod='scale'); background:none; }
.login					{border-radius:3px; position:relative; behavior: url(PIE.htc); }
.learn_more				{border-radius:3px; position:relative; behavior: url(PIE.htc); }
.get_acc				{border-radius:5px; position:relative; behavior: url(PIE.htc); }
.headerin p				{ text-shadow:0 0 1px #000000; position:relative; behavior: url(PIE.htc); }
 </style>
 <![endif]-->

</head>

<body>
	<div class="wrapper">
	<script>
    $(function() {
      $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
          var target = $(this.hash);
          target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
          if (target.length) {
            $('html,body').animate({
              scrollTop: target.offset().top
            }, 1000);
            return false;
          }
        }
      });
    });
$(document).ready(function() {
    $("#step2").hide();
    $("#step3").hide();
    $("#emailForm").hide();
    $("#registerBtn").click(function(){
        $("#step1").hide();
        //alert('testing');
        $("#step2").show();
    })

	$("#emailFormToggle").click(function(){
        $("#step2").hide();
        $("#step3").show();
	})

});
      </script>
            <!-- Header Starts -->
            <div class="header">
                    <!--<div class="angle_list">
                        <a  href="#"><%= image_tag "angle-bg.png", alt: "Home", align: "right" %></a>
                        <div class="angle_hover">
                            <a  href="#">We’re raising on AngelList!</a>
                        </div><!--angle_hover
            		</div>-->
              <% unless user_signed_in? %>
                  <%= render "layouts/header_nav" %>
               <% end %>
                  <div class="icons">
                        <ul>
                            <li><a class="fbook" href="https://www.facebook.com/newappetite"></a></li>
                            <li><a class="twitter" href="https://www.twitter.com/newappetite"></a></li>
                            <li><a  class="email"href="mailto:support@newappetite.com"></a></li>
                        </ul><div class="clear"></div>
                    </div>
                    <!--<div class="right" style="float: right; padding-top: 45px; font-size: 15px;">
                        <%# if user_signed_in? %>
                        <a href="#" data-dropdown="drop" class="small primary radius button dropdown"><strong><%#= current_user.email %></strong></a><br>
                            <ul id="drop" data-dropdown-content class="f-dropdown">
                                <li><%#=link_to 'Edit profile', edit_user_registration_path %></li>
                                <li><%#= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                                <%# if current_user.invite_user == true %>
                                  <li><%#= link_to 'Admin', admin_root_path, method: :get %></li>
                                <%# end %>
                            </ul>
                        <%# else %>
                                <div class="login" href="/users/login" data-fancybox-type="ajax" ><%#= link_to 'Login', new_user_session_path%></div>
                        <%# end %>
                    </div>-->
                  <div>

                    </div>
                    <div class="clear"></div>
                   	<div class="logo"><a href="/"><%= image_tag "logo.png", alt: "logo" %></a></div>

app/views/layouts/_header_nav.html.erb
<div class="headerin" style="width:100%">
  <% if user_signed_in? %>
      <div class="nav-header">
        <h1>Newappetite New</h1>
        <ul class="header-item tabs" id="tabs">
          <% if current_user.superadmin == true %>
            <li><%= link_to 'Admin', admin_root_path, method: :get %></li>
          <% end %>
          <li><%= link_to 'Playlists', playlists_path, method: :get %></li>
          <li><%= link_to 'Tracks', "/tracks", method: :get %></li>
        </ul>
        <ul class="utility_nav">
          <li><%= link_to current_user.email, "/users/edit" %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
  <% else %>
      <div class="login" href="/users/login" data-fancybox-type="ajax" ><%= link_to 'Login', new_user_session_path%></div>
  <% end %>
 </div>

app/views/layouts/_profile.html.erb
<div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Profile Setting</h3>
        <small>Contact us at support@newappetite.com if you have any questions.</small>
      </div>
      <div class="modal-body" style="width: 600px; height: 415px;">

        <input type="hidden" value="<%= current_user.id unless current_user.id.nil?%>" id="user_id">
        <%= form_for :user, :url => update_profile_path, :html => {:multipart => true} do |f| %>
        <div class="panel" style="float: left; width: 225px; height: 336px;">
          <div>
            <%= f.label :profile_pic, :style => "margin-left: 42px;" %><br />
            <div class="" style="width: 159px;height: 184px;" id="profile_image">
              <img src='<%= @user.profile_pic unless @user.profile_pic.nil?%>' height=130 width=130 class="img-circle" style="border: 1px solid #CCCCCC;margin-left:28px"/>
              <%= f.file_field :profile_image,:id=>"profile_pic", :style=>"margin: 5px; width: 200px;" %>
            </div>
          </div>
          <div>
            <%= f.label :cover_photo, :style => "margin-left: 42px;" %>
            <div class="" style="width: 159px;height: 184px;" id="cover_image">
              <img src='<%= @user.cover_pic unless @user.cover_pic.nil?%>' height=130 width=130 class="img-thumbnail" style="border: 1px solid #CCCCCC;margin-left:28px"/>
              <%= f.file_field :cover_image,:id=>"cover_pic", :style=>"margin: 5px; width: 200px;" %>
            </div>
           </div>
        </div>

        <div class="panel" style="float: right; width: 325px; height: 336px;">
            <div class="form-group">
              <%= f.label :profile_name %>
              <%= f.text_field :profile_name, :class => "form-control" %>
              <small>Profile names can differ from account names</small>
            </div>
            <div class="form-group">
              <label class="">Social Media</label>
              <%= f.text_field :facebook_link, :class => "form-control",:placeholder => "Facebook"%></br>
              <%= f.text_field :twitter_link, :class => "form-control", :placeholder => "Twitter" %></br>
              <%= f.text_field :website_link, :class => "form-control", :placeholder => "Website"%>
              <small>Social media links will be displayed on your profile</small>
            </div>

          <div class="form-group">
            <label class="">Location</label>
            <%= f.text_field :location, :class => "form-control" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit :update, :class => "btn btn-primary" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<head>
  <meta charset="utf-8">
  <title>MyChoice</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'header', media: 'all' %>
    <%= stylesheet_link_tag 'bootstrap', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
</head>

<body>
    <%= render "layouts/header_nav" %>
    <p class="alert-notice"><%= flash[:alert] %></p>

    <%= yield %>
</body>

<script type="text/javascript">

        $(document).ready(function(){
            setTimeout(function(){
                if($('.alert-notice').html() != null && $('.alert-notice').html() != ""){
                    $('.alert-notice').slideUp();
                }
            }, 3000);
        })

</script>